### ISSUE TITLE
a wee suggestion about the mouse cursors...

### ISSUE THREAD

**Issue by joedefen** [ivan-hc/Aisleriot-appimage#1]
Thanks for the AppImage and the other great AppImages, too.

My wee suggestion, if you care to address it, is that the cursors are too small, especially the hand cursor hovering over cards.  Example below:
![teeny-cursor-aisleriot](https://github.com/ivan-hc/Aisleriot-appimage/assets/23245364/176c5c5b-b23e-4515-9a86-4c718a6c3475)

It does make the game double as "Where's Waldo" -)  The cursor is about the size of a leaf of the a clover as you can (barely) see on the 8-of-clubs.

I don't understand ins-and-outs of building appimages, to be sure, but  I find it odd that it adapts to my dark theme and uses my (large) theme cursors when hovering over the menu bar at the top, etc., and then the cursors shrink over the playing area.  Arrrgh.

As you wish.  Great job otherwise.  Sometimes the "essential" Bonded cardset is missing in Aisleriot, but you included that ... don't mess with that ;-)

**Comment by ivan-hc** [comment]
Try now, I added the package "adwaita-cursors" and a keyword in /usr/share for "icons". Here are the changes:
- https://github.com/ivan-hc/Aisleriot-appimage/commit/7bc7b27a865d5ddacbebecdd7c8c72ac63fbd4cd
- https://github.com/ivan-hc/Aisleriot-appimage/commit/f3784ed773f4290feed89d901760ddf765b6fa21

this should fix the issue.

**Comment by joedefen** [comment]
Bummer, no difference in my tests of getting the new version from both appman and directly from releases here.

**Comment by ivan-hc** [comment]
its really strange, have you tried to reinstall this via appman?

**Comment by joedefen** [comment]
OK. Mark I'll mark it fixed/closed.  I was only trying it on my high res desktop monitor (that looked to me like it had not changed).  But on my laptop, aisleriot is now looking great ... big hand cursor. Not sure exactly why it is the way it is.  But, I run i3 on my desktop (where I run apps that crap out on Wayland) and sway on my laptop.  So ... apples and oranges in play.  Weird, but I'm quite happy ;-)  Thanks.
